name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: c-hive/gha-yarn-cache@v2
      - name: Install JS dependencies
        run: yarn install
      - name: TS - check
        run: yarn check-types
